ALTER TABLE accounts ADD COLUMN note VARCHAR(255);
ALTER TABLE expenses ADD COLUMN note VARCHAR(255);
ALTER TABLE incomes ADD COLUMN note VARCHAR(255);
ALTER TABLE categories ADD COLUMN note VARCHAR(255);